apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana-oauth
  description: A service that handles authentication for our public grafana instance
  annotations:
    operate-first.cloud/logo-url: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
    argocd/app-name: grafana-smaug
    github.com/project-slug: operate-first/apps
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=grafana-oatuh'
  links:
    - url: https://github.com/operate-first/apps/issues/new
      title: Support path
      icon: user
    - url: https://github.com/operate-first/apps/tree/master/grafana/overlays/moc/smaug
      title: Manifests
      icon: web
spec:
  type: service
  lifecycle: production
  owner: group:operate-first
  system: grafana
  dependsOn:
    - resource:smaug
    - component:dex
  consumesApis:
    - dex
