apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: components
  description: A collection of all operate-first services
spec:
  targets:
    - ./components/argocd.yaml
    - ./components/dex.yaml
    - ./components/grafana/grafana-oauth.yaml
    - ./components/grafana/grafana-public.yaml
    - ./components/backstage.yaml
    - ./components/crunchy-postgres-db.yaml
